INSERT INTO T_MATERIAS (ID_T_MATERIAS, NOMBRE, ACTIVO) VALUES (null, 'matematicas', 1);
INSERT INTO T_MATERIAS (ID_T_MATERIAS, NOMBRE, ACTIVO) VALUES (null, 'programacion', 1);
INSERT INTO T_MATERIAS (ID_T_MATERIAS, NOMBRE, ACTIVO) VALUES (null, 'ingenieria de sofware', 1);
INSERT INTO T_ALUMNOS (ID_T_USUARIOS, NOMBRE, AP_PATERNO, AP_MATERNO, ACTIVO) VALUES (null, 'John', 'Dow', 'Down', 1);